package controller;

import javafx.event.ActionEvent;
import javafx.event.Event;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.ContextMenu;
import javafx.scene.control.Label;
import javafx.scene.control.MenuItem;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.Tab;

public class StatController {
	@FXML
	private Button endButton;
	@FXML
	private Label cursorDateLabel;
	@FXML
	private Tab orderTab;
	@FXML
	private ComboBox orderBox;
	@FXML
	private Tab machineTab;
	@FXML
	private ComboBox machineList;
	@FXML
	private ContextMenu chartMenu;
	@FXML
	private ScrollPane scrollPane;
	@FXML
	private MenuItem refreshMenuItem;
	@FXML
	private MenuItem updateMenuItem;

	// Event Listener on Button[#endButton].onAction
	@FXML
	public void endActionButton(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void refreshMaps(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Tab[#orderTab].onSelectionChanged
	@FXML
	public void orderTabEvent(Event event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#orderBox].onAction
	@FXML
	public void chooseOrder(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Tab[#machineTab].onSelectionChanged
	@FXML
	public void machineTabEvent(Event event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#machineList].onAction
	@FXML
	public void machineChoose(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#refreshMenuItem].onAction
	@FXML
	public void refreshEvent(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#refreshMenuItem].onAction
	@FXML
	public void refreshChart(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#updateMenuItem].onAction
	@FXML
	public void updateChart(ActionEvent event) {
		// TODO Autogenerated
	}
}
